name: Clojars Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.12.0.1530'
      - name: Cache All The Things
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
      - name: Switch to Project Directory
        run: cd projects/intracel-core
      #- name: Install Dependencies
      #  run: clojure -T:deps
      - name: Build Uberjar
        run: clojure -T:build uberjar
      - name: Publish to Clojars
        env:
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USER }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_KEY }}
        run: clojure -T:build deploy :snapshot false
      
        