name: Clojars Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set Git Tag Variable
        run: echo "GIT_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.12.0.1530'
      - name: Cache All The Things
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}
      - name: Install Polylith
        run: | 
          wget https://github.com/polyfy/polylith/releases/download/v0.2.21/poly-0.2.21.jar
          sudo mkdir -p /usr/local/polylith
          sudo mv poly-0.2.21.jar /usr/local/polylith/ 
          sudo cp scripts/poly /usr/local/bin/poly        
      - name: Switch to Project Directory
        run: cd projects/intracel-core
      #- name: Install Dependencies
      #  run: clojure -T:deps
      - name: Run Tests
        run: |
          source ./set-jvm-opts.sh
          poly test
      - name: Build Library Jar
        env:
          VERSION: ${{ env.GIT_TAG }} # Pass the tag to the build script
        run: clojure -T:build libjar :project intracel-core
      - name: Publish to Clojars
        env:
          VERSION: ${{ env.GIT_TAG }} # Pass the tag to the build script
          CLOJARS_USERNAME: ${{ secrets.CLOJARS_USER }}
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_KEY }}
        run: clojure -T:build deploy :project intracel-core